export const Users = [
    {
      id:1,
      profilePicture: "assets/person/2.jpeg",
      username: "Rajeev Sharma",
    },
    {
      id:2,
      profilePicture: "assets/person/1.jpeg",
      username: "Brijesh Gupta",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpeg",
      username: "Dipak Gautam",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Mushir Ul haq",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Ajay Sharma",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: "Nagendra Bahadur",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Said ji",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Pirem Chopra",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "Haria Sharma",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Karan singh ",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      name:"Rajeev Sharma",
      desc: "Hey friends how are you 😺",
      photo: "assets/post/post3.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      name:"Brijesh Gupta",
      desc: "Its business.",
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      name:"Dipak Gautam",
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      name:"Mushir Ul Haq",
      desc: "When life gives you lemons, make lemonade",
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      name:"Pirem Chopra",
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      name:"Ajay Sharma",
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      name:"Hariom Sh",
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      name:"Said khan",
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      name:"Nagendra Bahadur",
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      name:"Shamsher Ansari",
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];